#!/bin/bash
set -e

# Build DATABASE_URL from secret if DB password file exists
if [ -f "/run/secrets/vaultwarden_db_password" ]; then
    DB_PASSWORD="$(cat /run/secrets/vaultwarden_db_password)"
    # Use DB_HOST from environment or default to 'mariadb'
    DB_HOST="${DB_HOST:-mariadb}"
    export DATABASE_URL="mysql://vaultwarden:${DB_PASSWORD}@${DB_HOST}:3306/vaultwarden"
    echo "DATABASE_URL configured for MySQL (host: ${DB_HOST})"
fi

# Check if keys directory is mounted from host (at /data/keys)
if [ -d "/data/keys" ]; then
    echo "Storage Box keys directory mounted at /data/keys"
    
    # Create symlink from /data/rsa_key.pem to Storage Box location
    if [ ! -L "/data/rsa_key.pem" ]; then
        # If key exists in Storage Box, use it
        if [ -f "/data/keys/rsa_key.pem" ]; then
            echo "Using existing RSA key from Storage Box"
            ln -sf /data/keys/rsa_key.pem /data/rsa_key.pem
            ln -sf /data/keys/rsa_key.pub.pem /data/rsa_key.pub.pem
        else
            # Will be generated by Vaultwarden, then moved by post-start script
            echo "RSA key will be generated and moved to Storage Box"
            /usr/local/bin/post-start.sh &
        fi
    fi
fi

# Start registry client in background if enabled
if [ "${ENABLE_REGISTRY:-true}" = "true" ]; then
    echo "Starting go-proxy registry client..."
    /usr/local/bin/registry-client &
    REGISTRY_PID=$!
    echo "Registry client started (PID: $REGISTRY_PID)"
    
    # Trap signals to ensure registry client is also terminated
    trap "echo 'Shutting down registry client...'; kill $REGISTRY_PID 2>/dev/null; wait $REGISTRY_PID 2>/dev/null" SIGTERM SIGINT
fi

# Execute original Vaultwarden entrypoint
exec /start.sh "$@"
