#!/bin/bash
set -e

# Mount Storage Box for RSA keys if enabled
if [ "${STORAGE_BOX_KEYS_ENABLED}" = "true" ]; then
    echo "Mounting Storage Box for RSA keys..."
    
    # Create mount point
    mkdir -p "${STORAGE_BOX_KEYS_MOUNT_POINT}"
    
    # Read password from secret file
    if [ -f "${STORAGE_BOX_PASSWORD_FILE}" ]; then
        STORAGE_BOX_PASSWORD=$(cat "${STORAGE_BOX_PASSWORD_FILE}")
    fi
    
    # Mount Storage Box via CIFS
    if ! mountpoint -q "${STORAGE_BOX_KEYS_MOUNT_POINT}"; then
        mount -t cifs \
            "//${STORAGE_BOX_HOST}/backup${STORAGE_BOX_KEYS_PATH}" \
            "${STORAGE_BOX_KEYS_MOUNT_POINT}" \
            -o "username=${STORAGE_BOX_USER},password=${STORAGE_BOX_PASSWORD},${STORAGE_BOX_KEYS_MOUNT_OPTIONS}"
        
        echo "Storage Box mounted at ${STORAGE_BOX_KEYS_MOUNT_POINT}"
    fi
    
    # Create symlink from /data/rsa_key.pem to Storage Box location
    if [ ! -L "/data/rsa_key.pem" ]; then
        # If key exists in Storage Box, use it
        if [ -f "${STORAGE_BOX_KEYS_MOUNT_POINT}/rsa_key.pem" ]; then
            echo "Using existing RSA key from Storage Box"
            ln -sf "${STORAGE_BOX_KEYS_MOUNT_POINT}/rsa_key.pem" /data/rsa_key.pem
            ln -sf "${STORAGE_BOX_KEYS_MOUNT_POINT}/rsa_key.pub.pem" /data/rsa_key.pub.pem
        else
            # Will be generated by Vaultwarden, then moved by post-start script
            echo "RSA key will be generated and moved to Storage Box"
            /usr/local/bin/post-start.sh &
        fi
    fi
fi

# Execute original Vaultwarden entrypoint
exec /start.sh "$@"
