#!/bin/sh
set -eu

STATE_DIR="${CF_REALIP_STATE_DIR:-/tmp/cf-realip}"
API_URL="${CF_IPS_API_URL:-https://api.cloudflare.com/client/v4/ips}"
OUT_FILE="${CF_REALIP_OUT:-${STATE_DIR}/cloudflare_realip.conf}"
ETAG_FILE="${CF_REALIP_ETAG:-${STATE_DIR}/cloudflare_ips.etag}"
STATUS_FILE="${CF_REALIP_STATUS:-${STATE_DIR}/cf-realip.status.json}"
TMP_FILE="${OUT_FILE}.tmp"
BAK_FILE="${OUT_FILE}.bak"

# Ensure paths & status file
mkdir -p "$(dirname "$OUT_FILE")" "$(dirname "$ETAG_FILE")" "$(dirname "$STATUS_FILE")"

# Initialize with valid placeholder content if missing/empty
if [ ! -f "$STATUS_FILE" ] || [ ! -s "$STATUS_FILE" ]; then
  printf '{"last_ok_iso":"","last_ok_ts":0,"last_error":"init","last_etag":"","consecutive_failures":0}\n' > "$STATUS_FILE"
fi

# Initialize etag with a placeholder so it's never empty
if [ ! -f "$ETAG_FILE" ] || [ ! -s "$ETAG_FILE" ]; then
  printf 'pending' > "$ETAG_FILE"
fi

status_ok() {
  NEW_ETAG="$1"
  NOW_ISO="$(date -u '+%Y-%m-%dT%H:%M:%SZ')"; NOW_TS="$(date -u +%s)"
  
  # Write status to temp file first, then atomic rename
  STATUS_TMP="${STATUS_FILE}.tmp.$$"
  printf '{"last_ok_iso":"%s","last_ok_ts":%s,"last_error":"","last_etag":"%s","consecutive_failures":0}\n' \
    "$NOW_ISO" "$NOW_TS" "$NEW_ETAG" > "$STATUS_TMP"
  mv -f "$STATUS_TMP" "$STATUS_FILE"
  
  # Write etag to temp file first, then atomic rename
  ETAG_TMP="${ETAG_FILE}.tmp.$$"
  printf '%s' "$NEW_ETAG" > "$ETAG_TMP"
  mv -f "$ETAG_TMP" "$ETAG_FILE"
}

status_err() {
  MSG="$1"; CF=0
  if [ -s "$STATUS_FILE" ]; then CF="$(jq -r '.consecutive_failures // 0' <"$STATUS_FILE" 2>/dev/null || echo 0)"; fi
  CF=$((CF+1))
  LAST_OK_ISO="$(jq -r '.last_ok_iso // ""' <"$STATUS_FILE" 2>/dev/null || true)"
  LAST_OK_TS="$(jq -r '.last_ok_ts // 0' <"$STATUS_FILE" 2>/dev/null || true)"
  
  # Write to temp, then atomic rename
  STATUS_TMP="${STATUS_FILE}.tmp.$$"
  printf '{"last_ok_iso":"%s","last_ok_ts":%s,"last_error":"%s","last_etag":"%s","consecutive_failures":%s}\n' \
    "$LAST_OK_ISO" "$LAST_OK_TS" "$(printf %s "$MSG" | tr '\n' ' ')" \
    "$(cat "$ETAG_FILE" 2>/dev/null || echo "")" "$CF" > "$STATUS_TMP"
  mv -f "$STATUS_TMP" "$STATUS_FILE"
}

# Fetch Cloudflare JSON
JSON="$(curl -fsSL "$API_URL")" || { status_err "fetch_failed"; exit 1; }
NEW_ETAG="$(printf '%s' "$JSON" | jq -r '.result.etag // empty' 2>/dev/null || echo "")"

# If ETag unchanged, mark success and exit
if [ -n "$NEW_ETAG" ] && [ -f "$ETAG_FILE" ] && [ "$NEW_ETAG" = "$(cat "$ETAG_FILE" 2>/dev/null || true)" ]; then
  status_ok "$NEW_ETAG"
  echo "[cloudflare-realip] No change (etag unchanged)."
  exit 0
fi

# Render new config
{
  echo "# AUTOGENERATED by update-cf-ips.sh - DO NOT EDIT"
  echo "# Source: $API_URL"
  echo "# Last-Update: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
  echo ""
  echo "real_ip_header CF-Connecting-IP;"
  echo "real_ip_recursive on;"
  printf '%s\n' "$JSON" | jq -r '.result.ipv4_cidrs[] | "set_real_ip_from \(.);"' || true
  printf '%s\n' "$JSON" | jq -r '.result.ipv6_cidrs[] | "set_real_ip_from \(.);"' || true
} > "$TMP_FILE"

# Skip reload if identical
if [ -f "$OUT_FILE" ] && cmp -s "$TMP_FILE" "$OUT_FILE"; then
  rm -f "$TMP_FILE"
  [ -n "$NEW_ETAG" ] && printf '%s' "$NEW_ETAG" > "$ETAG_FILE"
  status_ok "$NEW_ETAG"
  echo "[cloudflare-realip] No change (config identical)."
  exit 0
fi

# Swap + validate, then reload by HUP PID 1
[ -f "$OUT_FILE" ] && cp -f "$OUT_FILE" "$BAK_FILE" || true
mv -f "$TMP_FILE" "$OUT_FILE"
chmod 0644 "$OUT_FILE"

if nginx -t >/dev/null 2>&1; then
  kill -HUP 1 || { status_err "nginx_reload_failed"; exit 1; }
  [ -n "$NEW_ETAG" ] && printf '%s' "$NEW_ETAG" > "$ETAG_FILE"
  rm -f "$BAK_FILE" 2>/dev/null || true
  status_ok "$NEW_ETAG"
  echo "[cloudflare-realip] Updated and reloaded."
else
  [ -f "$BAK_FILE" ] && mv -f "$BAK_FILE" "$OUT_FILE" || true
  status_err "nginx_test_failed"
  echo "[cloudflare-realip] nginx -t failed; rolled back." >&2
  exit 1
fi
