[program:registry-agent]
command=/usr/local/bin/pelican-registry-agent
autostart=%(ENV_SUPERVISORD_CADDY)s
autorestart=true
priority=20
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
redirect_stderr=true